#!/usr/bin/env python3
"""Generate the parts of the website that are derived from the repository.

Two things are generated rather than written by hand, because a copy of something is a copy that
goes stale:

  site/assets/bhupura.svg   from the Kotlin that every surface of the app draws its mark with
  site/privacy.html         from docs/PRIVACY.md, which is the policy of record

Run it with --check to verify the generated files match their sources without writing anything;
that is what CI does, so a change to the mark or the policy cannot quietly leave the site behind.

    python3 scripts/build_site.py
    python3 scripts/build_site.py --check
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLYPH = ROOT / "app/src/main/java/ie/shoonya/yantra/ui/components/YantraGlyph.kt"
POLICY = ROOT / "docs/PRIVACY.md"
SITE = ROOT / "site"


# --------------------------------------------------------------------------------------- the mark

def bhupura_svg() -> str:
    """Translate `bhupuraPath` from the Kotlin into an SVG path.

    The Kotlin builds the path in a 28-unit design space and scales it; the units are what we want,
    so `u` is read as 1 and the viewBox is 28 wide. Parsing the source rather than transcribing the
    numbers is the point: the mark is defined in exactly one place and this stays honest to it.
    """
    source = GLYPH.read_text()
    body = re.search(r"internal fun bhupuraPath\(s: Float\): Path \{(.*?)\n\}", source, re.S)
    if not body:
        raise SystemExit("could not find bhupuraPath in %s — has it been renamed?" % GLYPH)

    commands: list[str] = []
    for call in re.finditer(r"(moveTo|lineTo|quadraticTo)\(([^)]*)\)", body.group(1)):
        name, args = call.group(1), call.group(2)
        numbers = [float(n) for n in re.findall(r"(-?[\d.]+)\s*\*\s*u", args)]
        if name == "moveTo":
            commands.append("M%g %g" % tuple(numbers))
        elif name == "lineTo":
            commands.append("L%g %g" % tuple(numbers))
        else:
            commands.append("Q%g %g %g %g" % tuple(numbers))
    commands.append("Z")

    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28" fill="none" '
        'stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round">\n'
        "  <!-- Generated by scripts/build_site.py from YantraGlyph.kt. Do not edit. -->\n"
        '  <path d="%s"/>\n'
        "</svg>\n" % " ".join(commands)
    )


# ------------------------------------------------------------------------------------ the policy

def markdown_to_html(text: str) -> str:
    """Enough Markdown for the privacy policy, and no more.

    A dependency to render one document that this repository already controls the shape of would be
    a dependency to keep current. Headings, paragraphs, lists, tables, bold, italic, code and links
    is all `docs/PRIVACY.md` uses, and anything it grows beyond that will show up as literal
    Markdown on the page rather than silently disappearing.

    Two things are easy to get wrong and were: the source hard-wraps its paragraphs, so consecutive
    lines are one paragraph and not several; and the policy has a table, which is the part a reader
    most wants to skim.
    """
    lines = text.splitlines()
    out: list[str] = []
    i = 0

    def inline(s: str) -> str:
        s = html.escape(s)
        s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", s)
        s = re.sub(r"_([^_]+)_", r"<em>\1</em>", s)
        s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', s)
        return s

    def cells(row: str) -> list[str]:
        return [c.strip() for c in row.strip().strip("|").split("|")]

    def is_divider(row: str) -> bool:
        return bool(re.fullmatch(r"\s*\|?[\s:|-]+\|?\s*", row)) and "-" in row

    while i < len(lines):
        line = lines[i].strip()

        if not line or line == "---":
            i += 1
            continue

        heading = re.match(r"^(#{1,4})\s+(.*)$", line)
        if heading:
            level = len(heading.group(1))
            out.append("<h%d>%s</h%d>" % (level, inline(heading.group(2)), level))
            i += 1
            continue

        # A table: a header row, a divider, then rows until the block ends.
        if line.startswith("|") and i + 1 < len(lines) and is_divider(lines[i + 1]):
            head = cells(line)
            i += 2
            body = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                body.append(cells(lines[i]))
                i += 1
            out.append("<table><thead><tr>%s</tr></thead><tbody>%s</tbody></table>" % (
                "".join("<th>%s</th>" % inline(c) for c in head),
                "".join("<tr>%s</tr>" % "".join("<td>%s</td>" % inline(c) for c in row)
                        for row in body),
            ))
            continue

        if line.startswith(("- ", "* ")):
            items = []
            while i < len(lines) and lines[i].strip().startswith(("- ", "* ")):
                # A wrapped list item continues on the next indented line.
                item = lines[i].strip()[2:]
                i += 1
                while (i < len(lines) and lines[i].startswith(("  ", "\t"))
                       and lines[i].strip() and not lines[i].strip().startswith(("- ", "* "))):
                    item += " " + lines[i].strip()
                    i += 1
                items.append(item)
            out.append("<ul>%s</ul>" % "".join("<li>%s</li>" % inline(x) for x in items))
            continue

        # An ordinary paragraph, which the source hard-wraps: gather until a blank line.
        para = []
        while i < len(lines) and lines[i].strip() and not lines[i].strip().startswith(("#", "- ", "* ", "|")) \
                and lines[i].strip() != "---":
            para.append(lines[i].strip())
            i += 1
        out.append("<p>%s</p>" % inline(" ".join(para)))

    return "\n".join(out)


def privacy_html() -> str:
    body = markdown_to_html(POLICY.read_text())
    return """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy — Yantra</title>
<meta name="description" content="Yantra collects nothing. There is no Yantra server and no account with us.">
<link rel="icon" href="assets/bhupura.svg" type="image/svg+xml">
<link rel="stylesheet" href="assets/style.css">
</head>
<body class="prose-page">
<!-- Generated by scripts/build_site.py from docs/PRIVACY.md. Do not edit. -->
<main class="prose">
<p class="back"><a href="index.html">Yantra</a></p>
%s
</main>
</body>
</html>
""" % body


# ------------------------------------------------------------------------------------------ main

TARGETS = {
    "assets/bhupura.svg": bhupura_svg,
    "privacy.html": privacy_html,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if a generated file is missing or out of date")
    args = parser.parse_args()

    stale: list[str] = []
    for relative, build in TARGETS.items():
        path = SITE / relative
        wanted = build()
        if args.check:
            if not path.exists() or path.read_text() != wanted:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted)
            print("wrote site/%s" % relative)

    if stale:
        print("These are generated from the repository and no longer match it:", file=sys.stderr)
        for relative in stale:
            print("  site/%s" % relative, file=sys.stderr)
        print("Run: python3 scripts/build_site.py", file=sys.stderr)
        return 1
    if args.check:
        print("site is in step with the repository")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
